main2_2

load pima_test.txt;
load pima_train.txt;

probability_y_1 = size(class_1, 1)/(size(class_1, 1)+size(class_0, 1));
probability_y_0 = size(class_0, 1)/(size(class_1, 1)+size(class_0, 1));


ycapnb = zeros(size(pima_train, 1),3);
for i=1:size(pima_train, 1)
    probability_0 =   exppdf(pima_train(i,1), exp_0_1_muhat)*...
            exppdf(pima_train(i,5), exp_0_5_muhat)*...
            exppdf(pima_train(i,7), exp_0_7_muhat)*...
            exppdf(pima_train(i,8), exp_0_8_muhat)*...
            normpdf(pima_train(i,2),norm_0_2_mu,norm_0_2_sigma)*...
            normpdf(pima_train(i,3),norm_0_3_mu,norm_0_3_sigma)*...
            normpdf(pima_train(i,4),norm_0_4_mu,norm_0_4_sigma)*...
            normpdf(pima_train(i,6),norm_0_6_mu,norm_0_6_sigma)*...
            probability_y_0;
    probability_1 =   exppdf(pima_train(i,1), exp_1_1_muhat)*...
            exppdf(pima_train(i,5), exp_1_5_muhat)*...
            exppdf(pima_train(i,7), exp_1_7_muhat)*...
            exppdf(pima_train(i,8), exp_1_8_muhat)*...
            normpdf(pima_train(i,2),norm_1_2_mu,norm_1_2_sigma)*...
            normpdf(pima_train(i,3),norm_1_3_mu,norm_1_3_sigma)*...
            normpdf(pima_train(i,4),norm_1_4_mu,norm_1_4_sigma)*...
            normpdf(pima_train(i,6),norm_1_6_mu,norm_1_6_sigma)*...
            probability_y_1;
    
    ycapnb(i,1) = predict_NB(probability_0, probability_1);
    ycapnb(i,2) = probability_1/(probability_1+probability_0);
    ycapnb(i,3) = pima_train(i,9);
end


ytestcapnb = zeros(size(pima_test, 1),3);
for i=1:size(pima_test, 1)
    probability_0 =   exppdf(pima_test(i,1), exp_0_1_muhat)*...
            exppdf(pima_test(i,5), exp_0_5_muhat)*...
            exppdf(pima_test(i,7), exp_0_7_muhat)*...
            exppdf(pima_test(i,8), exp_0_8_muhat)*...
            normpdf(pima_test(i,2),norm_0_2_mu,norm_0_2_sigma)*...
            normpdf(pima_test(i,3),norm_0_3_mu,norm_0_3_sigma)*...
            normpdf(pima_test(i,4),norm_0_4_mu,norm_0_4_sigma)*...
            normpdf(pima_test(i,6),norm_0_6_mu,norm_0_6_sigma)*...
            probability_y_0;
    probability_1 =   exppdf(pima_test(i,1), exp_1_1_muhat)*...
            exppdf(pima_test(i,5), exp_1_5_muhat)*...
            exppdf(pima_test(i,7), exp_1_7_muhat)*...
            exppdf(pima_test(i,8), exp_1_8_muhat)*...
            normpdf(pima_test(i,2),norm_1_2_mu,norm_1_2_sigma)*...
            normpdf(pima_test(i,3),norm_1_3_mu,norm_1_3_sigma)*...
            normpdf(pima_test(i,4),norm_1_4_mu,norm_1_4_sigma)*...
            normpdf(pima_test(i,6),norm_1_6_mu,norm_1_6_sigma)*...
            probability_y_1;
    
    ytestcapnb(i,1) = predict_NB(probability_0, probability_1);
    ytestcapnb(i,2) = probability_1/(probability_1+probability_0);
    ytestcapnb(i,3) = pima_test(i,9);
end

% C_test and C_train are the confusion matrices
C2nb = confusionmat(pima_test(:,9),ytestcapnb(:,1))
Cnb = confusionmat(pima_train(:,9),ycapnb(:,1))
 misclassificationErrorTrainingnb=(Cnb(1,2)+Cnb(2,1))/(Cnb(2,1)+Cnb(2,2)+Cnb(1,1)+Cnb(1,2))
 misclassificationErrorTestingnb=(C2nb(1,2)+C2nb(2,1))/(C2nb(2,1)+C2nb(2,2)+C2nb(1,1)+C2nb(1,2))
 sensetivitynb=(Cnb(2,2))/(Cnb(2,2)+Cnb(2,1))
specificitynb=(Cnb(1,1))/(Cnb(1,2)+Cnb(1,1))
sensetivitytestnb=(C2nb(2,2))/(C2nb(2,2)+C2nb(2,1))
specificitytestnb=(C2nb(1,1))/(C2nb(1,2)+C2nb(1,1))


